name: webspark_test
description: "Тестове завдання"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-82.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  STATE MANAGEMENT
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0

  #  NAVIGATION
  auto_route: ^7.8.4

  #  NETWORK
  dio: ^5.4.1

  #  LOCAL STORAGES
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #  UTILS
  flutter_screenutil: ^5.9.0
  formz: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
